apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: morgan-svc
spec:
  type: NodePort
  selector:
    app: morgan-nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080