name: Deploy to Kubernetes via ArgoCD

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/

    - name: Login to ArgoCD
      env:
        ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      run: |
        # 로그인 시 --insecure 옵션을 추가할 수도 있습니다.
        argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure

    - name: Sync ArgoCD Application
      id: sync
      run: |
        argocd app sync morgan || exit 1

    - name: Rollback on Failure
      if: failure()
      run: |
        echo "Sync failed, initiating rollback..."
        # 예시로 롤백 대상 revision을 지정하거나 최신 안정 버전으로 롤백
        argocd app rollback morgan